#application
spring:
  application:
    name: location-service

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: driver-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.rideshare.location_service.event.DriverAvailabilityUpdateEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8082